### ISSUE TITLE
Moving/Sharing PyPI of fmcapi

### ISSUE THREAD

**Issue by daxm** [marksull/fmcapi#109]
I completely forgot to move/share the pypi "location" for fmcapi with you.  We should get in contact and figure out how to do this.  That said, I *think* that if I new your pypi user I could make you a co-owner easily enough.

**Comment by marksull** [comment]
Good call mate. I didn't have a PyPi until about 30 seconds ago. Userid marksull.

**Comment by daxm** [comment]
Add you as owner.
