### ISSUE TITLE
AccessPolicy - Category creation

### ISSUE THREAD

**Issue by rgomez-eng** [marksull/fmcapi#110]
Hi,

Is there any way to create categories in Access Policies?

Thanks,

**Comment by marksull** [comment]
No. Looking at the code it doesn't appear that has been implemented yet.

If the category is already defined in the ACP then you can assign a rule to it, but this will fail if the category has not already been created.

```
rule = AccessRules(fmc=fmc_session, acp_name="mark-test", category="marks")
```

**Comment by rgomez-eng** [comment]
Any plans to implement it?

**Comment by marksull** [comment]
Not immediately, no. This is an open source project so if you want to contribute and send a Pull Request we always welcome extra contributions.

**Comment by rgomez-eng** [comment]
Absolutely. Just checking if there was something ongoing.

Thanks :)
