### ISSUE TITLE
"after_auto" Manual NAT rules

### ISSUE THREAD

**Issue by jmattatall** [marksull/fmcapi#111]
**Is your feature request related to a problem? Please describe.**
Unable to add Manual NAT rules "after_auto" defaults to "before_auto"
We are migrating from ASA to FTD and wanted to keep the rule structure the same.
I was able to modify the manualnatrules.py by adding codes related to "section" from the accessrules.py script
I'm not a programmer so it was a lot of trial and error but it finally worked.
Just wondering if you could make that official.
Thanks, your work has been indispensable for me in building scripts for our network team and as I mentioned, I'm not a programmer, having examples is what really made the difference from other tools.

**Comment by marksull** [comment]
Can you provide the details of what changes you made to get the outcome you desired?

**Comment by jmattatall** [comment]
Sure, here is the script in txt
[manualnatrules.txt](https://github.com/marksull/fmcapi/files/7500133/manualnatrules.txt)

**Comment by marksull** [comment]
Thanks for contributing the code for this fix @jmattatall
