### ISSUE TITLE
Support for overrides

### ISSUE THREAD

**Issue by lavermil** [marksull/fmcapi#122]
Do you have any overrides support? I did a repo search for "overrid" and found nothing so I am guessing there is no support for it. Can you confirm if you do or do not?

TIA.

**Describe the solution you'd like**
Support for overrides for anything that supports override. Typical usage would be for host, network, range, fqdn, network groups, ports, and port groups when you want to use the same object name in the ACP but have the value change based on the sensor for which the ACP/object/etc is deployed to.

**Describe alternatives you've considered**
other than manually doing it or writing my own code no options. :(

**Additional context**
n/a

**Comment by marksull** [comment]
No, sorry. Happy to accept a Pull Request with the enhancement though ;-)
