### ISSUE TITLE
fmcapi is being installed using the legacy 'setup.py install' method

### ISSUE THREAD

**Issue by dalamanster** [marksull/fmcapi#137]
hello, 
can you please update the pip package to new standards? 

When using 'pip install fmcapi' following warning is displayed:

> DEPRECATION: fmcapi is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

Removal of setup.py install  is targeted to pip 23.1 (April 2023).

Thanks

**Comment by marksull** [comment]
Done.
