### ISSUE TITLE
unusedOnly and nameOrValue filter options for object lookups

### ISSUE THREAD

**Issue by manofcolombia** [marksull/fmcapi#157]
**Is your feature request related to a problem? Please describe.**
Currently integrating FMC into a hail mary ip address searching tool that we use internally. The input is specifically the ip address/cidr and can not rely on knowing the object id or object name. It doesn't look like we are currently able to take advantage of the newer filters for getting /objects/(hosts,networks,etc.).

These newer filters seem to have been added 7.0+, but, as usual, that seems to be difficult to confirm from the cisco docs:

unusedOnly:true
`/api/fmc_config/v1/domain/{UUID}/object/hosts?filter=unusedOnly%3Atrue`

nameOrValue:$nameOrValue
`/api/fmc_config/v1/domain/{UUID}/object/hosts?filter=nameOrValue%3A10.253.96.55'`

**Describe the solution you'd like**
I am currently looking at contributing to solve this, but I was looking for validation that there isn't an existing way to do this.

**Describe alternatives you've considered**
I tried using `/search/object/` instead, but I found that that endpoint doesn't evaluate group membership. We sometimes use this for decommissioning purposes so it is important to us to know if a host object is a member of any groups.

Example:

10.253.128.54 is a host object and that host object is also within another group.

`/search/object/` will return only the host object, and network objects that 10.253.128.54 is a part of (10.0.0.0/8)

`/object/hosts?filter=nameOrValue%3A10.253.96.55` will return the host object, any group objects that the host object is a member of, and will not result in the extra objects like 10.0.0.0/8 since the call is just to `/objects/hosts` instead of `objects`.

**Additional context**
`unusedOnly:true` is somewhat of a tangent to this current use case, but we can probably just handle `?filter=` so we can accommodate any future filters Cisco decides to bless us with.

**Comment by marksull** [comment]
Merged
