### ISSUE TITLE
/object/operational/usage Endpoint not supported

### ISSUE THREAD

**Issue by manofcolombia** [marksull/fmcapi#159]
**Is your feature request related to a problem? Please describe.**
We use extended ACLs for RAVPN DAP implementation. The find usage in the GUI is broken in dark mode and pretty lack luster in light mode - it'll show you if an object is in an extended ACL but won't let you pivot/open the ACL to show you where/how its used. So we're going to build our own find usage app tailored to our needs.

**Describe the solution you'd like**
I'll be working on a contribution that will support this api endpoint. This endpoint also uses the query filters handling referenced in #158 

**Describe alternatives you've considered**
There isn't really an alternative to using this endpoint to grab every location than an object is referenced.

**Comment by marksull** [comment]
Merged.
