### ISSUE TITLE
Is it possible to create sub-interfaces on an Etherchannel with fmcapi?

### ISSUE THREAD

**Issue by jmattatall** [marksull/fmcapi#99]
I've got an HA pair and I'm trying to create a bunch of etherchannel subinterfaces. It seems that I can create them on physical interfaces.

**Comment by jmattatall** [comment]
OK, I found out how, just had to change the subinterface api to say Etherchannel instead of PhysicalInterface and import Etherchannelinterfaces as well

**Comment by marksull** [comment]
Thanks for contributing for this fix @jmattatall
